export const companyRoles:{[key:string]:string[]} = {
    Google: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "UX Researcher",
      "AI/ML Engineer",
      "Site Reliability Engineer"
    ],
    Amazon: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "Data Scientist",
      "Logistics Manager",
      "Fulfillment Associate"
    ],
    Microsoft: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "Program Manager",
      "Security Analyst",
      "Cloud Architect"
    ],
    IBM: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "Blockchain Developer",
      "Mainframe Specialist",
      "Data Governance Expert"
    ],
    Accenture: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "Functional Consultant",
      "SAP Specialist",
      "Change Management Expert"
    ],
    Infosys: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "Test Analyst",
      "Delivery Manager",
      "Domain Consultant"
    ],
    Salesforce: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "CRM Administrator",
      "Platform Architect",
      "Solution Engineer"
    ],
    Cognizant: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "Business Analyst",
      "QA Engineer",
      "Healthcare BPO"
    ],
    TCS: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "RPA Developer",
      "Business Process Consultant",
      "ITIL Service Manager"
    ],
    Wipro: [
      "Account Executive",
      "Sales Engineer",
      "Business Development Manager",
      "Customer Success Manager",
      "Software Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer",
      "Infrastructure Engineer",
      "Support Engineer L2/L3",
      "Network Analyst"
    ],
    Zoho: [
      "Software Engineer",
      "Product Manager",
      "DevOps Engineer",
      "Customer Success Manager",
      "Sales Engineer",
      "UX Designer",
      "Solution Architect",
      "Technical Account Manager",
      "Salesforce Engineer"
    ],
    "4iapps": [
      "Software Engineer",
      "Functional Consultant",
      "Sales Engineer",
      "Delivery Manager",
      "DevOps Engineer",
      "Business Analyst",
      "Customer Success Manager",
      "Solution Architect",
      "Technical Account Manager"
    ],
    Oracle: [
      "Software Engineer",
      "Cloud Engineer",
      "DevOps Engineer",
      "Product Manager",
      "Solution Architect",
      "Sales Engineer",
      "Database Administrator",
      "Technical Account Manager",
      "Customer Success Manager"
    ],
    HCL: [
      "Software Engineer",
      "DevOps Engineer",
      "Technical Support",
      "Business Analyst",
      "Product Manager",
      "Solution Architect",
      "Technical Account Manager",
      "Sales Engineer",
      "Customer Success Manager"
    ],
    Capgemini: [
      "Software Engineer",
      "Functional Consultant",
      "SAP Consultant",
      "Product Manager",
      "DevOps Engineer",
      "Solution Architect",
      "Technical Account Manager",
      "Customer Success Manager",
      "Sales Engineer"
    ]
  };
  